// @ts-check

/**
 * Explicit, and organised by what somebody is trying to do.
 *
 * It used to be three categories - For Contributors, For Maintainers,
 * Technical Reference - which is the shape of the team that wrote the docs
 * rather than the shape of the questions people arrive with. A contributor
 * looking for "when do I get paid" had to know that lived under a
 * twelve-item contributor list, below "Notifications", while How Rewards
 * Work floated at the root between the two audience sections.
 *
 * Contributor-facing material is now grouped by task. Maintainer material
 * stays grouped by role, because for a maintainer the role IS the task -
 * they arrive to list a project and review applications, not to browse.
 *
 * Files are deliberately NOT moved: every page keeps its URL, so existing
 * links and bookmarks still resolve. That leaves paths like
 * /docs/contributors/social-follow under a category called "Rewards and
 * eligibility". Worth revisiting with redirects if this structure settles.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: [
        'contributors/getting-started',
        'maintainers/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Finding and doing work',
      collapsed: false,
      items: [
        'contributors/finding-work',
        'contributors/applying-to-issues',
        'contributors/grainhack',
      ],
    },
    {
      // The pages that answer "what do I get, and what do I have to do to
      // qualify". Rewards used to sit at the root, outside both audience
      // sections, which is where a page goes when nobody decides where it
      // belongs.
      type: 'category',
      label: 'Rewards and eligibility',
      collapsed: false,
      items: [
        'rewards',
        'contributors/referrals',
        'contributors/social-follow',
      ],
    },
    {
      type: 'category',
      label: 'Your account',
      collapsed: false,
      items: [
        'contributors/verifying-your-identity',
        'contributors/profile',
        'contributors/ranks-and-leaderboard',
        'contributors/notifications',
        'contributors/getting-help',
      ],
    },
    {
      type: 'category',
      label: 'For maintainers',
      collapsed: true,
      link: {type: 'doc', id: 'maintainers/getting-started'},
      items: [
        'maintainers/ecosystems-and-events',
        'maintainers/managing-applications',
        'maintainers/reviewing-pull-requests',
        'maintainers/keeping-projects-in-sync',
        'maintainers/maintainer-dashboard',
        'maintainers/grainhack',
      ],
    },
    {
      // Out of the contributor navigation, but findable and searchable.
      // Someone who joined when points existed will search "redeem" and
      // deserves an answer; that answer is a changelog entry, not a feature
      // sitting in the nav beside things that work.
      type: 'doc',
      id: 'what-changed',
      label: 'What changed',
    },
    {
      // For people working on Grainlify itself, not people using it.
      type: 'category',
      label: 'Technical reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    /*
     * Last, collapsed, and named so nobody mistakes it for current.
     *
     * These pages documented five Soroban contracts. One exists, and it has
     * never been deployed. They sat in Technical Reference, where a reader -
     * including a grant reviewer - would reasonably take them as a
     * description of a working system. A banner is a label; the section a
     * page sits in is where people actually navigate from, so they moved.
     */
    {
      type: 'category',
      label: 'Archive (never built)',
      collapsed: true,
      link: {type: 'doc', id: 'archive/index'},
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
  ],
};

export default sidebars;
