// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit, not autogenerated from the whole tree: this site serves two
 * different audiences. Contributors and maintainers need their guides first
 * and uncluttered; the Soroban contract/API reference underneath is for
 * developers working on Grainlify itself, so it's nested one level down
 * under its own collapsed category instead of sitting alongside the guides
 * as equally-weighted top-level sections.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'For Contributors',
      link: {type: 'doc', id: 'contributors/getting-started'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'contributors'}],
    },
    {
      type: 'category',
      label: 'For Maintainers',
      link: {type: 'doc', id: 'maintainers/getting-started'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'maintainers'}],
    },
    {
      type: 'category',
      label: 'Technical Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
