// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Explicit, not autogenerated from the whole tree: this site serves two
 * different audiences. Contributors and maintainers need their guides first
 * and uncluttered; the Soroban contract/API reference underneath is for
 * developers working on Grainlify itself, so it's nested one level down
 * under its own collapsed category instead of sitting alongside the guides
 * as equally-weighted top-level sections.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'For Contributors',
      link: {type: 'doc', id: 'contributors/getting-started'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'contributors'}],
    },
    {
      type: 'doc',
      id: 'rewards',
      label: 'Rewards',
    },
    {
      type: 'category',
      label: 'For Maintainers',
      link: {type: 'doc', id: 'maintainers/getting-started'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'maintainers'}],
    },
    {
      type: 'category',
      label: 'Technical Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    /*
     * Last, collapsed, and named so nobody mistakes it for current.
     *
     * These pages documented five Soroban contracts. One exists, and it has
     * never been deployed. They sat in Technical Reference, where a reader -
     * including a grant reviewer - would reasonably take them as a
     * description of a working system. A banner is a label; the section a
     * page sits in is where people actually navigate from, so they moved.
     */
    {
      type: 'category',
      label: 'Archive (never built)',
      collapsed: true,
      link: {type: 'doc', id: 'archive/index'},
      items: [{type: 'autogenerated', dirName: 'archive'}],
    },
  ],
};

export default sidebars;
